name: shapefactoryforadms
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.1

dependencies:
  dio: ^5.7.0
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.3
  http: ^1.2.0
  http_parser: ^4.0.2
  loading_animation_widget: ^1.3.0
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  minSdk: 24
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/