name: shapefactoryforadms
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.1

dependencies:
  dio: ^5.7.0
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.3
  http: ^1.2.0
  http_parser: ^4.0.2
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/