-- SELECT --
SELECT * FROM SF.Client;
SELECT * FROM SF.Adm;
SELECT * FROM SF.Exercise;
SELECT * FROM SF.Muscle;
SELECT * FROM SF.Recipe;

-- DELETE --
DELETE FROM SF.Client;
DELETE FROM SF.Adm;
DELETE FROM SF.Exercise;
DELETE FROM SF.Muscle;
DELETE FROM SF.Recipe;

-- DROP TABLE --
DROP TABLE SF.Client;
DROP TABLE SF.Adm;
DROP TABLE SF.Exercise;
DROP TABLE SF.Muscle;
DROP TABLE SF.Recipe;

-- SERIAL RESET --
ALTER SEQUENCE SF.Client_client_id_seq RESTART WITH 1;
ALTER SEQUENCE SF.Adm_adm_id_seq RESTART WITH 1;
ALTER SEQUENCE SF.Exercise_exercise_id_seq RESTART WITH 1;
ALTER SEQUENCE SF.Muscle_muscle_id_seq RESTART WITH 1;
ALTER SEQUENCE SF.Recipe_recipe_id_seq RESTART WITH 1;